### ISSUE TITLE
Error installation using pip install ...

### ISSUE THREAD

**Issue by AgusTor92** [PolyChord/PolyChordLite#100]
Hello,
I'm a new user of pypolychord package. I'm having problems installing pypolychord via pip install git...
The main issue is that cannot open include mpif.h. 

I'm using a subsystem of Linux WSL2 Ubuntu in Windows 11.

**Comment by williamjameshandley** [comment]
You will need to install prerequisites (such as openmpi and gfortran) within your ubuntu install in order to compile PolyChord
