### ISSUE TITLE
Mac install libchord.so issue

### ISSUE THREAD

**Issue by htjb** [PolyChord/PolyChordLite#104]
Having trouble installing pypolychord on a Mac system. Running macOS 13.5 on an M2 max chip with python3.11. I went through different variants of install from source the simplest being

```bash
pip3 install https://github.com/PolyChord/PolyChordLite/archive/master.zip
```
and I consistently get the following error message

```bash
subprocess.CalledProcessError: Command '['make', '-e', 'libchord.so']' returned non-zero exit status 2.
```

when I run `make -e libchord.so` after git cloning the repo I get the following

```bash
/Library/Developer/CommandLineTools/usr/bin/make -C /Users/harrybevins/Documents/Software/PolyChordLite/src/polychord /Users/harrybevins/Documents/Software/PolyChordLite/lib/libchord.so
mpifort -shared abort.o array_utils.o calculate.o chordal_sampling.o clustering.o feedback.o generate.o ini.o interfaces.o maximiser.o mpi_utils.o nelder_mead.o nested_sampling.o params.o priors.o random_utils.o read_write.o run_time_info.o settings.o utils.o c_interface.o -o /Users/harrybevins/Documents/Software/PolyChordLite/lib/libchord.so -lc++ -install_name @loader_path/pypolychord/lib/libchord.so
ld: unknown options: -commons
collect2: error: ld returned 1 exit status
make[1]: *** [/Users/harrybevins/Documents/Software/PolyChordLite/lib/libchord.so] Error 1
make: *** [/Users/harrybevins/Documents/Software/PolyChordLite/lib/libchord.so] Error 2
```

Up until recently I had polychord working on this system with python3.8 but I upgraded python version and ran into issues.

Hopefully this is an obvious fix (don't use Mac) that I am just missing.

**Comment by htjb** [comment]
I ran

```bash
brew reinstall gcc
```

and it magically fixed the polychord install issue I was having.

**Comment by appetrosyan** [comment]
@williamjameshandley can we reopen this issue?

**Comment by appetrosyan** [comment]
This flag is automatically inserted due to the default GCC configuration. When reinstalling, the configuration is updated, and the `-commons` flag, which was a crutch is being removed.
