### ISSUE TITLE
unable to install. Error related to mpixx

### ISSUE THREAD

**Issue by mudit-jain90** [PolyChord/PolyChordLite#106]
Hi,

I'm trying to install polychord, using "python setup.py install" in the terminal. However, it eventually returns with the following error 

clang: error: linker command failed with exit code 1 (use -v to see invocation)
error: command '/opt/homebrew/bin/mpicxx' failed with exit code 1

I'd be glad to receive any assistance please.
Thanks!
PS: I'm installing it on Mac

**Comment by mudit-jain90** [comment]
HI,

I have been struggling with issues related to `commons', and unable to install Polychord. It's been over 2 months and I hope the developers can find some time to resolve this issue.

I have been trying to install Polychord on my Mac, but it spits out the following error:

<img width="712" alt="Screenshot 2023-12-15 at 1 18 59 AM" src="https://github.com/PolyChord/PolyChordLite/assets/84209375/67d31449-0709-416c-bc37-5dea77ebf680">

I'd be glad to receive any assistance please.
Thanks!
PS: I notice that there was another issue that got opened, related to commons. But looks like no progress has been made so far...

**Comment by williamjameshandley** [comment]
closing given #109

**Comment by mudit-jain90** [comment]
It doesn't work. I've updated brew, and have reinstalled gcc. The same error comes again. Please open this ticket again.
