### ISSUE TITLE
build requires numpy

### ISSUE THREAD

**Issue by steven-murray** [PolyChord/PolyChordLite#26]
Since you require numpy to be installed in an environment _before_ running `setup.py`, could you include `pyproject.toml` and have a section:

```
[build-system]
requires = ["numpy"]
```

This will enable `pypolychord` to be built without first manually installing numpy (very useful for some CI builds).

**Comment by williamjameshandley** [comment]
This sounds very reasonable. Could you submit a pull request with this file added to make check that this works with this repository's CI?

**Comment by williamjameshandley** [comment]
Fixed by #80
