### ISSUE TITLE
Errors while using PyPolyChord example

### ISSUE THREAD

**Issue by sayrjked** [PolyChord/PolyChordLite#31]
I installed PyPolyChord using the instructions provided [here](https://github.com/PolyChord/PolyChordLite#python-likelihoods-pypolychord)

When I am trying to run the example using the following command, I am getting the error below. 
Command used: `python run_pypolychord.py`

```
Traceback (most recent call last):
  File "run_pypolychord.py", line 46, in <module>
    output = pypolychord.run_polychord(likelihood, nDims, nDerived, settings, prior, dumper)
  File "~/PolyChordLite/pypolychord/__init__.py", line 231, in run_polychord
    settings.seed)
TypeError: run() takes exactly 32 arguments (33 given)
```

I am not sure how to resolve it. It will be very helpful if someone is able to point me in right direction.

Thank you in advance.

**Comment by williamjameshandley** [comment]
Hi @sayrjked . Can you confirm that this issue occurs on a fresh install of polychord, making sure you've uninstalled any existing implementations (e.g. by repeatedly running pip uninstall pypolychord)? 

Currently this issue should show up in the test suite that we have, so I'd like to try to understand why this is occurring on your system.

**Comment by sayrjked** [comment]
Hello @williamjameshandley .
I was able to resolve the issue by `pip uninstall pypolychord` and fresh reinstalling the polychord. Thank you for your help.
