### ISSUE TITLE
Resuming on another computer

### ISSUE THREAD

**Issue by qminor** [PolyChord/PolyChordLite#38]
I am copying my chain output files to another computer cluster so I can resume the job there. I see there is both a "<label>.resume" and "<label>_temp.resume" files; do I need to copy both files over in order to resume? Or can I leave out the "temp" file? Since they take up a lot of space, I thought I should check.

Thanks,
Quinn

**Comment by williamjameshandley** [comment]
Hi @qminor,

You should definitely be able to copy across the resume files to another cluster and use them there. The `.resume` files are plain text (and therefore quite large) for precisely this portability purpose.

You don't need to copy the `_temp.resume` file. That is only there in case a run is killed in the middle of writing to the resume file.

Best,
Will
