### ISSUE TITLE
Compiling PolyChord on Cray

### ISSUE THREAD

**Issue by qminor** [PolyChord/PolyChordLite#39]
I need to compile Polychord on a Cray computer cluster using Cray compilers (cc, CC, ftn). Have you ever done this before? The compiler options are different than for intel so I am hoping you have already encountered this. Let me know--if not, I will forge ahead and try to get the administrators to help out.

Thanks,
Quinn

**Comment by williamjameshandley** [comment]
I have not, but it would be good to know how to get this done. Let me know what changes you needed to make (ideally via a PR) in order to get the Cray compilers working. Ideally you'd create a new `Makefile_cray` with an additional `$(COMPILER_TYPE)` switch in the main `Makefile`

**Comment by qminor** [comment]
Hi Will,

Thanks for your email. Yes, I will definitely make a Makefile_cray and am
happy to contribute.

I will pester the admins to help me out. My biggest worry, though, is that
there will be some compiler/version-specific problems with the code, and I
have very limited fortran experience. Is it alright if I ask you a few
questions about compiler errors if they come up? (Of course I will
troubleshoot first.) The project is time-sensitive, so I will be moving
fast on this.

Thanks,
Quinn

**Comment by williamjameshandley** [comment]
@qminor there are now some [Makefile_cray]( https://github.com/PolyChord/PolyChordLite/blob/d9f2d869ad33069837e0f74e571017b8429ab615/Makefile_cray) settings contributed by @Pablo-Lemos. These may be of help in getting to compile.
