### ISSUE TITLE
Gaussian example code & comment disagree

### ISSUE THREAD

**Issue by andrewfowlie** [PolyChord/PolyChordLite#45]
Very small thing. The comment and code disagree for sigma in the gaussian example program (1e-2 versus 1e-1):

https://github.com/PolyChord/PolyChordLite/blob/40022f52d37b3bd74e2f99c0e59d014899d24fb4/likelihoods/examples/gaussian.f90#L11

https://github.com/PolyChord/PolyChordLite/blob/40022f52d37b3bd74e2f99c0e59d014899d24fb4/likelihoods/examples/gaussian.f90#L28

I won't make a PR, as I'm not sure which one you want to change. FWIW, the equivalent MultiNest example uses 1e-3, so you might even want to change both.

**Comment by williamjameshandley** [comment]
Fixed by https://github.com/PolyChord/PolyChordLite/commit/691ee5f68b4f93b31fdd409d48762869e0d84aa5
