### ISSUE TITLE
Make PyPolyChord pip-installable. 

### ISSUE THREAD

**Issue by appetrosyan** [PolyChord/PolyChordLite#46]
This is one of the major missing features of PC, and shouldn’t be too difficult to implement.

**Comment by appetrosyan** [comment]
The work that needs to be done is 
1) to automate fetching dependencies 
2) to automate fetching build dependencies, which should be similar to how jumpy does it (they have fortran code too). 
3) test the reproducibility if the build on Windows, Linux and Mac OS X. 
4) add optional dependencies, 
5) handle MPI
6) expose 3, 4, 5 to pip in a standard way.

**Comment by williamjameshandley** [comment]
I believe that we were nearly here with #24. It looks like the only thing blocking this were OSX related issues. I suggest we move this conversation to there.
