### ISSUE TITLE
Speeds -- documentation and possible override?

### ISSUE THREAD

**Issue by JesusTorrado** [PolyChord/PolyChordLite#5]
Hi Will,

I cannot figure out the exact behaviour of speeds in PolyChord. The only documentation I can find on the usage of speeds is in `settings.py`, reading:

    grade_frac : List[float]
        (Default: 1)
        The amount of time to spend in each speed.
    grade_dims : List[int]
        (Default: 1)
        The number of parameters within each speed.

And some more in the examples:

    # e.g. if one has 3 speeds, then settings this as 
    # grade_frac = 0.6 0.2 0.2
    # will mean that polychord spends 60% of its time doing num_repeats 
    # in the slow parameter set, and the remaining 40% of its time on the other
    # two parameter sets, over sampling as is appropriate.
    # otherwise this should be set equal to 1

But what's `time` there? Does PolyChord make its own time measurements (it looks like it)? Or does it mean `proportion of likelihood evaluations`, as in `grade_frac = 0.6 0.2 0.2` would mean that of every 10 evaluations, [6,2,2] are done respectively on the three blocks, regardless of the actual evaluation time of the parameters in the block?

If it means `time as measured by PolyChord`, is there any way to override that? I am asking because (a) I already have good measurements of evaluation time, and (b) there is no guarantee that that time is correctly measured by PolyChord (e.g. some regions of the parameter space for a *slow* likelihood may evaluate to -infinity *immediately* after some error checking, making PolyChord believe that the likelihood is faster than it is).

Cheers

**Comment by williamjameshandley** [comment]
Hi Jesus,

PolyChord does make it's own time measurements. 

>(e.g. some regions of the parameter space for a slow likelihood may evaluate to -infinity immediately after some error checking, making PolyChord believe that the likelihood is faster than it is).

However, it discounts -infinity calculations from the timing, so this wouldn't be an issue.

> If it means time as measured by PolyChord, is there any way to override that?

I agree that this is functionality that people (myself included) would find useful.

How does the following interface sound:

1) if `grade_frac` contains a number `< 1`, then it does the timing as usual.
2) if all `grade_frac` are `>=1` (and would usually be entered as integers) e.g. `grade_frac = [4, 10, 100]`, then it uses those repeats, and does not time them itself.

If that's agreeable, I can implement that pretty quickly, but let me know if you had something different in mind

**Comment by JesusTorrado** [comment]
Understood. Good that the -inf results are discarded!

The proposed implementation looks good to me! A couple of notes:

- I can think of two different interpretations for an integer number: go over this full block `n` times, or go over parameters in this block `n` times (regardless of the number of parameters in the block). Either looks good to me (unless you want to impose *integer* `grade_frac`'s: in that case the second one is more flexible: allows for non-full-block passes).
- If non-full-block passes are allowed (i.e. drawing only `n<m` iterations in a block of size `m`), it's important to make sure that directions are randomized; otherwise only the first ones are sampled each time. You are very likely already doing this, but just in case.

Cheers!

**Comment by JesusTorrado** [comment]
Any update on this? Cheers!

**Comment by williamjameshandley** [comment]
Do the changes in PR #21 have the functionality you were envisaging?

**Comment by JesusTorrado** [comment]
Sounds like it, thanks! I'll try to test it tomorrow.

**Comment by JesusTorrado** [comment]
Testing, sorry for the delay!

I am getting some strange error, not sure if related to speeds: in `output.py`, line `self.avnlikeslice = float(line.split()[3])` fails, because it's trying to cast a parenthesis into a float (the content of `line` is ` <nlike>:        0.00    0.00   (    0.00    0.00 per slice )\n'`)

Let me know if you need more info. Cheers!

**Comment by JesusTorrado** [comment]
Maybe has to do with that line now containing number of likelihood evaluations per block?

**Comment by williamjameshandley** [comment]
It looks like this is related to #20 . I think the pull request that made the changes to output.py didn't take into account the possibility of different speeds, and only worked for the single speed.

**Comment by JesusTorrado** [comment]
Yes, it's apparently that same error, but i guess the fix is a little more complicated that changing the `[3]` by a `[4]`?

I don't have time to take a deeper look at that issue, but I will try to write a small override such that I can test the speeds-related changes and let you know about it asap.

For a future version, I would suggest writing that output as yaml. It may save you a couple of headaches when interpreting it programmatically.

**Comment by JesusTorrado** [comment]
Works fine! (modulo the errors in `output.py`)

One proposed trivial change: line 14 in `_array.hpp` could be changed to `if(!PyFloat_Check(obj) && !PyInt_Check(obj)) throw PythonException();`, in order to allow `grade_frac` to be a list of *integers*.

This should interact trivially with MPI, I guess? It would if each MPI process launches its own slice-chain, but I don't know if that's precisely the case.

**Comment by williamjameshandley** [comment]
OK, I've merged #21, and will soon merge in #22, which I believe fixes the output error.

>One proposed trivial change: line 14 in _array.hpp could be changed to if(!PyFloat_Check(obj) && !PyInt_Check(obj)) throw PythonException();, in order to allow grade_frac to be a list of integers.

Feel free submit a PR.

>This should interact trivially with MPI, I guess? It would if each MPI process launches its own slice-chain, but I don't know if that's precisely the case.

There shouldn't be any MPI issues with this. the number of repeats is synced between runs.
