### ISSUE TITLE
Can't install the Python3 version of PyPolyChord

### ISSUE THREAD

**Issue by appetrosyan** [PolyChord/PolyChordLite#53]
The provided installation instructions fail. 

**steps to reproduce**: fresh install,
``` make pypolychord && CC=cc CXX=c++ python setup.py install --user```

**expected result**: 
running `python3 run_polychord.py` should work. 

**actual result**: 
```
Traceback (most recent call last):
  File "run_pypolychord.py", line 2, in <module>
    import pypolychord
  File "/Users/app/Git/PolyChordLite/pypolychord/__init__.py", line 28, in <module>
    raise e
  File "/Users/app/Git/PolyChordLite/pypolychord/__init__.py", line 16, in <module>
    import _pypolychord
ModuleNotFoundError: No module named '_pypolychord'
```

**Comment by williamjameshandley** [comment]
Is the problem that you're trying to run with python3, but you installed with python, and these point to different versions on your system?

**Comment by appetrosyan** [comment]
Yes. Unfortunately the fix of using Python3 for both the install and the run doesn't work. 

```
python3 setup.py install --user
running install
error: can't combine user with prefix, exec_prefix/home, or install_(plat)base
```

**Comment by appetrosyan** [comment]
Should I add the adjusted `MakeFile` into the PR for #50 ?

**Comment by williamjameshandley** [comment]
I'm about to merge #24 in the next half-hour, which makes it pip installable will change things a fair amount. I would be interested to see if this issue persists there.

**Comment by appetrosyan** [comment]
Ok! Looking forward to testing it.
