### ISSUE TITLE
Weird Posterior - Problem in Both CosmoMC and Cobaya interface to new Polychord

### ISSUE THREAD

**Issue by vivianmiranda** [PolyChord/PolyChordLite#6]
Hello!

I have this weird bug that affects newer versions of Polychord - both in my private CosmoMC interface and in the Cobaya new interface. The posterior just disagree drastically with what we get from MCMC (on Polychord 1.09 that was not the case - everything worked fine) 

Here is a trivial example I tested on Cobaya

[t1.pdf](https://github.com/PolyChord/PolyChordLite/files/2669907/t1.pdf)

[EXAMPLE_POLYCHORD_2.txt](https://github.com/PolyChord/PolyChordLite/files/2669909/EXAMPLE_POLYCHORD_2.txt)

[EXAMPLE_MCMC_2.txt](https://github.com/PolyChord/PolyChordLite/files/2669911/EXAMPLE_MCMC_2.txt)

Thanks for helping me!

**Comment by vivianmiranda** [comment]
I have seen this bug with multiple dimensions, different datasets and always version > 1.09

**Comment by vivianmiranda** [comment]
And somehow the Evidence seems correct when comparing to Multinest...just the posteriors are crap..

**Comment by vivianmiranda** [comment]
Other members of DES collaboration have seen similar problems in the CosmoSiS interface

**Comment by vivianmiranda** [comment]
Hello!

It was a fresh install. Troxel has the same mistake in Cosmosis. I will ask him to join.

In CosmoMC I used CosmoChord with some adapts - but I will update.

Different people - in different interfaces - similar problems.

:(

Best
Vivian Miranda

On Dec 12, 2018, at 1:24 AM, Will Handley <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @vivianmiranda<https://github.com/vivianmiranda> ,

I ran your cobaya examples on my local setup, and found that they agreed:

[image]<https://user-images.githubusercontent.com/3708486/49856042-d43ef000-fde6-11e8-94bc-fbb2ed3cb51d.png>

Can you confirm that you get this issue on a fresh install of pypolychord from the github repository<https://github.com/PolyChord/PolyChordLite>, having removed all previous versions?

@JesusTorrado<https://github.com/JesusTorrado> Have you seen anything like this before?

Other members of DES collaboration have seen similar problems in the CosmoSiS interface

Could you copy these people in to this discussion?

my private CosmoMC interface

You might like to know that there is now a github repository for CosmoChord<https://github.com/williamjameshandley/CosmoChord>, forked from CosmoMC<https://github.com/cmbant/CosmoMC>. For your future work, you might like to fork from this to stay up-to-date with any further bug fixes.

**Comment by vivianmiranda** [comment]
Ah

I used getdist to plot it

Vivian Miranda

On Dec 12, 2018, at 5:56 AM, Miranda, Vivian - (vivianmiranda) <vivianmiranda@email.arizona.edu<mailto:vivianmiranda@email.arizona.edu>> wrote:

Hello!

It was a fresh install. Troxel has the same mistake in Cosmosis. I will ask him to join.

In CosmoMC I used CosmoChord with some adapts - but I will update.

Different people - in different interfaces - similar problems.

:(

Best
Vivian Miranda

On Dec 12, 2018, at 1:24 AM, Will Handley <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @vivianmiranda<https://github.com/vivianmiranda> ,

I ran your cobaya examples on my local setup, and found that they agreed:

[image]<https://user-images.githubusercontent.com/3708486/49856042-d43ef000-fde6-11e8-94bc-fbb2ed3cb51d.png>

Can you confirm that you get this issue on a fresh install of pypolychord from the github repository<https://github.com/PolyChord/PolyChordLite>, having removed all previous versions?

@JesusTorrado<https://github.com/JesusTorrado> Have you seen anything like this before?

Other members of DES collaboration have seen similar problems in the CosmoSiS interface

Could you copy these people in to this discussion?

my private CosmoMC interface

You might like to know that there is now a github repository for CosmoChord<https://github.com/williamjameshandley/CosmoChord>, forked from CosmoMC<https://github.com/cmbant/CosmoMC>. For your future work, you might like to fork from this to stay up-to-date with any further bug fixes.

**Comment by JesusTorrado** [comment]
Hi both,

(@vivianmiranda sorry, I've been quite busy. Will come back to the Cobaya issues shortly)

I've seen similar stuff happen one mode in a multimodal pdf has not been discovered: the normalisation of the posterior changes and modes appear larger (contours are larger) than in the actual posterior, but keep the same shape.

So probably a normalization problem (also possibly due to different prior normalisation?)

**Comment by vivianmiranda** [comment]
Hello!

I dont think is just normalization - because in more complicated setups the posterior look rubbish ( unfortunately I think I deleted my CosmoMC test cases since dowgrading to Polychord 1.09 solved the CosmoMC issues).

Best
Vivian Miranda

On Dec 12, 2018, at 6:22 AM, Jesús Torrado <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi both,

(@vivianmiranda<https://github.com/vivianmiranda> sorry, I've been quite busy. Will come back to the Cobaya issues shortly)

I've seen similar stuff happen one mode in a multimodal pdf has not been discovered: the normalisation of the posterior changes and modes appear larger (contours are larger) than in the actual posterior, but keep the same shape.

So probably a normalization problem (also possibly due to different prior normalisation?)

**Comment by williamjameshandley** [comment]
I can't attempt to fix this issue without a MWE (at the moment I just have your scripts, which produce the right answer for me on my machine). Please can you tell me:

* What version of PolyChord you are using (number, branch and git hash)
* What version of Cobaya you are using (number, branch and git hash)
* What you are using to plot the posteriors

**Comment by vivianmiranda** [comment]
Hello

Polychord - ef02bb6d94dca218c7d8daa98e8ac010022e457e - I think this is the most up-dated version

Cobaya - also the latest commit - 1e5506cb662555fbec65c8293d661fffc98572a7.

I use getdist to make the plots.

**Comment by matroxel** [comment]
I'm not sure what I can add to this concretely right now, since I don't have time to reproduce the testing setup in a way that I could be sure you could replicate, but I was seeing similar issues with reproducing the DES Y1 cosmic shear posterior using polychord relative to multinest within cosmosis. I was getting consistent evidences between the two (though not within the quoted uncertainty of either), but significantly different contours. I'll add more details when I have time.

**Comment by vivianmiranda** [comment]
Oh

I am so sorry! I found the mistake after an afternoon trying to hunt down. GetDist when doing both MCMC and Polychord were extracting 0.3 of burn from both. I think that happened every time.

I am so sorry for open that ticket - I usually am very careful in checking

Best
Vivian

On Dec 12, 2018, at 1:59 PM, matroxel <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm not sure what I can add to this concretely right now, since I don't have time to reproduce the testing setup in a way that I could be sure you could replicate, but I was seeing similar issues with reproducing the DES Y1 cosmic shear posterior using polychord relative to multinest within cosmosis. I was getting consistent evidences between the two (though not within the quoted uncertainty of either), but significantly different contours. I'll add more details when I have time.

**Comment by JesusTorrado** [comment]
It happens :)

Actually, I had already been thinking of adding a setting to GetDist to produce a warning when trying to remove burn-in from nested-sampled chains. I guess I should.

Cheers!

**Comment by williamjameshandley** [comment]
No worries @vivianmiranda , I'm glad we resolved this, and I know what to point people to in the future if we see similar results.

@JesusTorrado I would go further than a GetDist warning. Burn-in has no meaning for nested sampling, so it should be disabled/throw an exception in the event of people trying to implement it. I've posted an [issue](https://github.com/cmbant/getdist/issues/27#issue-390631142).

@vivianmiranda Do you think this was the cause of Troxel's issue?

**Comment by vivianmiranda** [comment]
Hello!

Thanks for being so kind! I am not sure about Troxel problems - but we can have my silly mistake in mind if it happens again!

Best
Vivian Miranda

On Dec 13, 2018, at 4:16 AM, Will Handley <notifications@github.com<mailto:notifications@github.com>> wrote:


No worries @vivianmiranda<https://github.com/vivianmiranda> , I'm glad we resolved this, and I know what to point people to in the future if we see similar results.

@JesusTorrado<https://github.com/JesusTorrado> I would go further than a GetDist warning. Burn-in has no meaning for nested sampling, so it should be disabled/throw an exception in the event of people trying to implement it. I've posted an issue<https://github.com/cmbant/getdist/issues/27#issue-390631142>.

@vivianmiranda<https://github.com/vivianmiranda> Do you think this was the cause of Troxel's issue?
