### ISSUE TITLE
gcc-10 Error: Type/Rank mismatch between actual argument at (1) and actual argument at (2)

### ISSUE THREAD

**Issue by lukashergt** [PolyChord/PolyChordLite#60]
After some updates I couldn't re-install PolyChord anymore, but got a lot of these errors:

```make
mpi_utils.F90:560:12:

  560 |             seed_point,            &!
      |            1
......
  650 |             empty_buffer,      &! not sending anything
      |            2
Error: Type mismatch between actual argument at (1) and actual argument at (2) (REAL(8)/INTEGER(4)).
```

These errors seems to be caused by gfortran-10 now enforcing type matching.

**As a workaround for now**: 
Adding the option `-fallow-argument-mismatch` to `FCFLAGS` in `Makefile_gnu` turns above errors into warnings.

**Comment by williamjameshandley** [comment]
Hi @lukashergt, I think this is fixed in master already -- was this using the most up to date version?

**Comment by lukashergt** [comment]
> Hi @lukashergt, I think this is fixed in master already -- was this using the most up to date version?

No this was using the latest release version. If it's already fixed, all the better. I'm afraid I can't confirm, though, since I've already got a new run going. Just thought I'd post this workaround in case it might be useful.

**Comment by williamjameshandley** [comment]
OK. It's now in release 1.18.1 (also updated on aur if you use that).
