### ISSUE TITLE
run_pypolychord.py not working on new CSD3 cclake 

### ISSUE THREAD

**Issue by lukashergt** [PolyChord/PolyChordLite#64]
### Error on cclake

Running `python run_pypolychord.py` on the cclake login nodes of CSD3 fails with:

```bash
Error in system call pthread_mutex_destroy: Device or resource busy
    ../../src/mpi/init/init_thread_cs.c:60
Abort(1091087) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Other MPI error, error stack:
MPIR_Init_thread(136): 
MPID_Init(939).......: 
MPIR_pmi_init(168)...: PMI2_Job_GetId returned 14
```

Can you reproduce this error @williamjameshandley ?

---

### Module environment

To work with the [new cascasde lake nodes on CSD3](https://docs.hpc.cam.ac.uk/hpc/user-guide/cclake.html) one is supposed to load the following module:

```bash
ssh yourid@login-cpu.hpc.cam.ac.uk
module purge
module load rhel7/default-ccl
```

Note: This loads the recommended intel 2020.2 compilers by default.

I additionally load:

```bash
module load gcc/9
module load python/3.8
module load cfitsio-3.410-intel-17.0.4-4qrgkot
```

I also set up a fresh virtualenv for python.

---

### (Py)PolyChord installation

`make` and `pip` don't show any errors:

```bash
cd PolyChordLite
make clean
make veryclean
make
CC=mpiicc CXX=mpiicpc python setup.py install
```

Only upon running `run_pypolychord.py` I get the error mentioned at the start.

**Comment by williamjameshandley** [comment]
Cheers for the very clear bug report @lukashergt 

> Can you reproduce this error @williamjameshandley ?

Yes.

I can also fix it if I run as

`mpirun -np 1 python run_pypolychord.py`

I have had this issue with other machines before, and basically it depends on the infelicities of a given MPI setup (which given the complexity of getting multiple cores to talk to other over infiniband etc is understandable).

**Comment by lukashergt** [comment]
Thanks, this works for me, too. Annoyingly `-np 2` does not work on the login node, but I've tried it out interactively and that worked fine.
