### ISSUE TITLE
Importing Pypolychord fails with TabError

### ISSUE THREAD

**Issue by MoritzThomasHuebner** [PolyChord/PolyChordLite#7]
Hi, I am trying to import pypolychord into my Python 3 environment but I'm getting this weird error:
This only happens in Python 3, it works fine in Python 2.
```
  File "/home/moritz/.local/lib/python3.6/site-packages/pypolychord/__init__.py", line 19, in <module>
    from .run import run
  File "/home/moritz/.local/lib/python3.6/site-packages/pypolychord/run.py", line 49
    loglike_type = CFUNCTYPE(c_double, c_int, POINTER(c_double), c_int, \
                                                                        ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by williamjameshandley** [comment]
Hi @MoritzThomasHuebner, There shouldn't be any `CFUNCTYPES` in pypolychord. Perhaps this is from an older installation? Does the issue persist if you remove `/home/moritz/.local/lib/python3.6/site-packages/pypolychord/` and reinstall?

**Comment by MoritzThomasHuebner** [comment]
Thanks @williamjameshandley, I still had remains of the 'old' pypolychord floating around in my environment. This is working now for me.
