### ISSUE TITLE
Polycord crashes Cobaya with large numbers of clusters 

### ISSUE THREAD

**Issue by Skipp1** [PolyChord/PolyChordLite#71]
When Polychord has more than 100 clusters, Cobaya crashes. This is because Polychord formats its output as:
```
...
log(Z_98)
log(Z_99)
log(Z_**) 
log(Z_**)
...
```
Due to this formatting Cobaya crashes trying to convert the string "**" to an int() on line 345 of cobaya/samplers/polychord/polychord.py

I have opened an issue with the Cobaya team and have been told to come here
https://github.com/CobayaSampler/cobaya/issues/190

**Comment by williamjameshandley** [comment]
Hi @Skipp1. This has been a bug I've been meaning to fix for a while, but the intricacies of Fortran's string manipulation meant I needed a little push. 

Could you check if you install polychord from the branch large_cluster_fix that this resolves your issue?

**Comment by Skipp1** [comment]
Yes the large_cluster_fix branch solves all the issues, 
Thanks
