### ISSUE TITLE
typo in README?

### ISSUE THREAD

**Issue by lukashergt** [PolyChord/PolyChordLite#77]
In the [README.rst](https://github.com/PolyChord/PolyChordLite#rootphys_live-birthtxt--rootdead-birthtxt) it says:

> ### [root]phys_live-birth.txt & [root]dead-birth.txt
> 
> These can be used to reconstruct a full nested sampling run, as well as simulate dynamic nested sampling. The format & contents of these two files are as follows: They have has ndims+nderived+2 columns. The first ndims+nderived columns are the ndim parameter values along with the nderived additional parameters that are being passed by the likelihood routine for PolyChord to save along with the ndims parameters. The ndims+nderived+2 column is the log-likelihood value. The ndims+nderived+1 column is the log-likelihood value that the point was born at. They are is identical to the [root]_phys_live.txt and [root]_dead.txt file, except for an additional column including the birth contours

The way I understand this the order of the columns for `n` sampling parameters and `m` derived parameters is supposedly:
```
param_1   param_2   ...   param_n   derived_1    derived_2   ...   derived_m   logL_birth   logL
```

However, I have the impression that the output actually is ordered as:

```
param_1   param_2   ...   param_n   derived_1    derived_2   ...   derived_m   logL   logL_birth
```

Could you confirm/refute that suspicion, @williamjameshandley ?

**Comment by williamjameshandley** [comment]
That's certainly what the [anesthetic](https://github.com/williamjameshandley/anesthetic/blob/ad78c426be5b0b69a63314650f8cf3a8d1779437/anesthetic/read/polychordreader.py#L20) reader assumes, and (fortunately!) that's also what the [polychord code](https://github.com/PolyChord/PolyChordLite/blob/cb169af2fde463649d0a5cced579f101a70fbabb/src/polychord/read_write.F90#L711-L714) does. I'll update the readme now. Many thanks @lukashergt

**Comment by williamjameshandley** [comment]
Closed by [this direct commit].(https://github.com/PolyChord/PolyChordLite/commit/d9f2d869ad33069837e0f74e571017b8429ab615)
