### ISSUE TITLE
Installing polychord on Github Actions on macos

### ISSUE THREAD

**Issue by steven-murray** [PolyChord/PolyChordLite#78]
Hi, I'd like to run CI on my application that depends on polychord on both macos and linux. The linux version is installing fine, but I can't seem to get the macos version to install at all. It keeps trying to use `f77` as the fortran compiler, and I don't understand why. Have you been able to get it to install on macos on Github Actions?

**Comment by williamjameshandley** [comment]
This is hopefully something which will be fixed with the cmake build, which generally makes os install substantially easier #76. Feel free to test out that branch/contribute to that PR if you find that it needs adjustment.
